In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

In [3]:
df

   rollno   name           city  age  marks
0     101  Roger     California   20     85
1     102    Sam         London   22     81
2     103  Peter          Paris   19     95
3     104   Alex             LA   18     91
4     105  Alexa  San Fransisco   21     92
5     106   John       New York   20     88

In [7]:
df[df['rollno']==103]

   rollno   name   city  age  marks
2     103  Peter  Paris   19     95